spring.application.name=giencoder-learn

spring.config.import=classpath:application-log.properties

scash.duplicate-prevention.default-max-retry=3

# PostgreSQL ???????
spring.datasource.url=jdbc:postgresql://localhost:5432/postgres
spring.datasource.username=postgres
spring.datasource.password=1234
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.hikari.data-source-properties.currentSchema=scash

# JPA settings
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# ?????????????????
amatls.tenant.delimiter=|

# Session settings
scash.session.ttl=2000

# ========================================================================================
#                                                                                  Logging
#                                                                                  =======
logging.level.org.dbflute = DEBUG
logging.level.org.docksidestage = DEBUG
logging.level.org.springframework.jdbc.datasource.DataSourceTransactionManager = DEBUG
logging.level.com.scash.wms=DEBUG